### ISSUE TITLE
Allow moving profiles between groups

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#19]
**Is your feature request related to a problem? Please describe.**
Some profiles of accounts I got in CG are moved to another organization, but I need to work there still.
So I wanted to separate it in CG as well and move the existing profile(s) to the new group.

![HB5pah46sF](https://user-images.githubusercontent.com/13333848/214807958-6ecbaa3e-f09c-4fe1-97c4-b3287003e764.png)

Currently, it isn't possible to drag+drop the profile from one group to another.

**Comment by rehanvdm** [comment]
I have had this before as well. I think instead of drag and drop I will rather add an action to the "right-click context menu" and maybe in the dialogue edit window. It is going to be too much customization to make this tree element do drag and drop.

**Comment by rehanvdm** [comment]
Fixed in v0.0.114, see [the changelog here](https://github.com/Systanics/CloudGlance/releases/tag/v0.0.114).
