### ISSUE TITLE
 Keyboard input isn't working in CloudFormation tab for profile + region

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#21]
**To Reproduce**
1. Go to 'CloudFormation'
2. Click on the InputField, right of the headline (Not the Stack InputField)
3. Try to type a profile with the keyboard
4. Same applies for the region InputField

**Expected behavior**
Keyboad input should be possible to find the profile / account and the region faster.

**Screenshots**

**Desktop (please be as specific as possible):**
Windows 10 

**App version (click on the "Boundaries" menu item or at the bottom of the settings page)**
Version 0.0.113

**Comment by rehanvdm** [comment]
I don't think those fields are searchable, you can only select now, should be an easy fix.

**Comment by rehanvdm** [comment]
Fixed in v0.0.114, see [the changelog here](https://github.com/Systanics/CloudGlance/releases/tag/v0.0.114).
