### ISSUE TITLE
Deleting groups (incl. assigned profiles)

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#23]
Currently, I can't find any button or menu item to delete a group.
Right-click on a group brings only "New Profile".
Even if I click in the menu bar "Edit / Delete" with on a selected group, nothing happens.

**Comment by rehanvdm** [comment]
I will add this to the list of Group + Profile improvements coming in the next release. In the mean while you can manually edit the JSON and delete the group you want. 

Given your json config is like this: 
``` json
{
  "Group A": [
    {
      "aws": [
        {
          "name": "Shared",
          "profileName": "systanics",
          ...
        },
        {
          "name": "Prod",
          "profileName": "systanics-prod",
          ...
        },
        {
          "name": "Development",
          "profileName": "systanics-dev",
          ...
        }
      ],
      "version": 1,
      "trackedSecurityGroups": [ ],
      "bastions": [ ],
      "icon": ""
    }
  ],

  "Group B": [
    {
        "aws": [ ],
        "version": 1,
        "trackedSecurityGroups": [  ],
        "bastions": [ ],
        "icon": ""
    }
   ]
}
```

If you wanted to delete `Group B` then you just remove the property and then the document will look like: 
``` json
{
  "Group A": [
    {
      "aws": [
        {
          "name": "Shared",
          "profileName": "systanics",
          ...
        },
        {
          "name": "Prod",
          "profileName": "systanics-prod",
          ...
        },
        {
          "name": "Development",
          "profileName": "systanics-dev",
          ...
        }
      ],
      "version": 1,
      "trackedSecurityGroups": [ ],
      "bastions": [ ],
      "icon": ""
    }
  ]
}
```

**Comment by rehanvdm** [comment]
Actually, this is embarrassing. I remember what I did/decided on now. I did not want to clutter up the AWS view and left that functionality only in the Configuration view only. So this supported, it is possible to Delete a Group.  

![image](https://user-images.githubusercontent.com/22810856/216511601-6f1bc938-bd82-4f97-833e-570571d20dcb.png)

**Comment by rehanvdm** [comment]
Closing this. If this does not work for you or if I didn't understand correctly, please reopen it.
