### ISSUE TITLE
When re-adding a profile to another group, the profile dialog gets stuck

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#24]
**To Reproduce**
1. Create a group 1
2. Create a group 2
3. Create a SSO profile A in group 1
4. Delete the SSO profile A in group 1
5. Add the SSO profile A in group 2

Step 5 will cause a freeze of the profile window.

**Expected behavior**
Profile A should be added to group 2.

**Desktop (please be as specific as possible):**
Windows 10

**App version (click on the "Boundaries" menu item or at the bottom of the settings page)**
Version 0.0.113

**Comment by rehanvdm** [comment]
Fixed in v0.0.114, see [the changelog here](https://github.com/Systanics/CloudGlance/releases/tag/v0.0.114).
