### ISSUE TITLE
Re-use SSO Token for multiple profiles

### ISSUE THREAD

**Issue by jweier** [Systanics/CloudGlance#25]
Hi - I have an environment where I can authenticate using SSO on the AWS CLI a single time and then I'm able to use that token to access multiple different accounts/roles without needing to reauthenticate. Currently, with CloudGlance, I need to sign into each account. Am I missing something or is this a limitation of CloudGlance?

Thanks!
-Jay

**Comment by rehanvdm** [comment]
Hey, sorry for the late reply, became a dad last week 😃

I think your issue is similar to this one right? https://github.com/Systanics/CloudGlance/issues/15 

On what version are you currently?

See my last reply in that issue, there is a video in the release notes that shows that it does work

**Comment by jweier** [comment]
Hey - Congrats on becoming a dad! And I'm impressed you even responded at all in that case! Usually it's survival mode for a while after becoming a first time parent.

I reviewed the other issue and it does indeed seem the same. I also watched the video from the release but it appears that the video is actually illustrating the problem. In the video, you click to login to the first account and you input username/pw/mfa. At that point, you've successfully authenticated and received an SSO token. Then, when you click on the 2nd and 3rd account you should be able to use that same SSO token without having to click the orange allow button. From my understanding, that orange allow button is essentially generating an additional SSO token. 

To compare to the native AWS CLI....I have a profile that uses my AWS SSO Start URL. Once I input username/pw/mfa to that I receive an SSO token. After that, any profile which uses the same SSO Start URL uses the token that was already issued and doesn't need to authenticate again. 

Does that make sense? It's also the same for the AWS SSO GUI. Once you login once, you can click on any of your accounts and launch them without having to re-authenticate or click the orange allow button.

-Jay

**Comment by rehanvdm** [comment]
Hey, I explained this in that issue a bit and just recreated that what CloudGlance is doing is precisely the same as the CLI. I am reusing the SSO token between profiles that have the same `sso_start_url`.

My test (AWS CLI: `aws-cli/2.5.3 Python/3.9.11`): 

```
aws sso login --profile rehan-sso-dev
```
Opens browser and:
> Prompts for username
> Prompts for password 
> Prompts for MFA 
> Prmopts for "Allow"

```
aws sso login --profile rehan-sso-prod
```
Opens browser and: 
> Prmopts for "Allow"

Both have the same `sso_start_url` and other details, the only thing that differs is `sso_account_id` for the AWS dev and prod accounts. 

Can you maybe do a similar test and see what your results are? As I can still not recreate it as it is not an issue with CloudGlance, it is how SSO works with AWS, we can not get around that. (I guess I can maybe with a bit of puppeteer to click on the "Allow" button for us, not sure)

**Comment by jweier** [comment]
So, that's correct for the login action but you don't need to do a second login if you use the same start URL. In your example, `aws sso login --profile rehan-sso-dev` should prompt for the username/pw/MFA, that makes sense. However, if you also have a second profile (rehan-sso-prod) which uses the same SSO Start URL then you don't need to issue an `aws sso login` for that profile. Instead, you can just go directly to your commands like `aws s3 ls --profile rehan-sso-prod`. 

Does that clarify it?

**Comment by rehanvdm** [comment]
I see so in my previous test, I forgot to add the test AWS command, which I did run but did not mention. 

```
aws sso login --profile rehan-sso-dev
```
Opens browser and:
> Prompts for username
> Prompts for password 
> Prompts for MFA 
> Prmopts for "Allow"

**Then I run `aws s3 ls --profile rehan-sso-dev`**

```
aws sso login --profile rehan-sso-prod
```
Opens browser and: 
> Prmopts for "Allow"

**Then I run `aws s3 ls --profile rehan-sso-prod`**

---

And what you are saying, and I just tested, is that I don't need to do the secondary `aws sso login --profile rehan-sso-prod`. This means on my side within CloudGlance, I will just have to tie all the profiles together to use one token for each SSO StartURL and Role.

Yeah I can explore the above and see how I can make it work

**Comment by rehanvdm** [comment]
@michaelfecher this is what you meant by your issue right?

**Comment by jweier** [comment]
> 

So, it's actually a little different than what you're saying. After you've issued the first login command you can start running any commands on profiles which share that same SSO Start URL. For example, I have 3 profiles that share the same SSO Start URL and that my account has permissions to access, they are Dev, Test, Prod. I only need to authenticate one of them. So, I can do the following:

`aws sso login --profile Dev`
Provide the credentials, click the Orange allow button

Now I'm authenticated for any profiles that use that same SSO Start URL. So, I can do the following commands and I'm not asked for credentials or asked to hit the orange allow button. It just executes the command:

`aws s3 ls --profile Test`
`aws s3 ls --profile Prod`

The key difference that I'm seeing between your example and my experience is that when using profiles which share the same SSO Start URL you only need to authenticate and hit the orange allow button the very first time you login to any one of them. Once that's done, all subsequent profiles are fully authenticated and just run the commands. Of course, this requires that the account that you've authenticated with has access to all of the other profiles (which it does in my case). 

-Jay

**Comment by rehanvdm** [comment]
Yeah, that is how I have it as well, thanks for the extra info.

**Comment by rehanvdm** [comment]
Fixed in https://github.com/Systanics/CloudGlance/releases/tag/v0.0.121
