### ISSUE TITLE
Auto import existing AWS profiles

### ISSUE THREAD

**Issue by rehanvdm** [Systanics/CloudGlance#7]
**Is your feature request related to a problem? Please describe.**
User friction. I want to automatically add/import all my AWS profiles as Cloud Glance profiles. 

**Describe the solution you'd like**
Maybe a modal where you select a group first then a list view(searchable) of all your AWS profiles with check boxes next to them. You then select the profiles that you want in bulk and say import.

Alternatively, maybe we can create a "Default" group that has all your AWS profiles in it at first startup. Then have the ability to easily "move" the profile to another group. Maybe this must also be a modal, to select more than 1 at a time.

**Comment by michaelfecher** [comment]
When will this be addressed approx.? :)

**Comment by rehanvdm** [comment]
I am planning a release with enhancements on the profiles first, like Move and Copy. Then this is next on the list. So let's say maybe in the next two weeks to play it safe.

**Comment by rehanvdm** [comment]
Released in https://github.com/Systanics/CloudGlance/releases/tag/v0.0.117
