### ISSUE TITLE
Images for group icons  

### ISSUE THREAD

**Issue by all4miller** [Systanics/CloudGlance#9]
Would be nice to have client logos for Groups specially when you have allot.

**Comment by rehanvdm** [comment]
I am currently using these icons https://materialdesignicons.com/, there are a ton of them, so I can maybe make a drop-down and then you can select one of these? Or would you like to upload your own image maybe 🤔? 

Actually thinking about that, images would be more difficult to sync with import/export options available for profiles.

**Comment by rehanvdm** [comment]
@all4miller Group icons is now available in the latest release, you will also see that Profiles can now have a color https://github.com/Systanics/CloudGlance/releases/tag/v0.0.112 

>Actually thinking about that, images would be more difficult to sync with import/export options available for profiles.

FYI The solution I landed on was to crop the image to 100x100 and store it as base64 inside the JSON file.
